[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
[[services.ports]]
port = 8080
protocol = "HTTP"